title: Services
#preset: page

tabs:

  # content tab
  content:
    label: Inhalt
    icon: text
    columns:
      # main
      left:
        width: 2/3
        sections:
          content:
            type: fields
            fields:
              headline:
                type: text
                label: Headline
                width: 1/2
              text:
                type: textarea
                label: Text
                width: 1/2
          services:
            headline: List of services
            type: pagetable
            status: all
            sortable: false
            limitOptions:
              - 10
              - 25
              - 50
            template: service

      # sidebar
      right:
        width: 1/3
        sections:
          # a list of files
          files:
            headline: Dateien
            type: files

  # seo tab
  seo:
    label: SEO
    icon: search
    fields:
      seoSettings:
        label: SEO Einstellungen
        type: headline
      seo:
        extends: fields/seo
