title: Site

tabs:
  content:
    label: Seiten
    icon: dashboard
    columns:
        - width: 1/1
          sections:
            mainsites:
              layout: cardlets
              headline: Hauptseiten
              type: pages
              info: "{{ page.IntroText }}"
              image: falsese
              status: listed

            unlisted:
              layout: cardlets
              headline: Nicht veränderbare Seiten
              type: pages
              info: "{{ page.IntroText }}"
              image: falsese
              status: unlisted

            draft:
              layout: cardlets
              headline: Entwürfe
              type: pages
              info: "{{ page.IntroText }}"
              image: falsese
              status: draft
              create:
                - default
                - comments
                - contact
                - about
                - services

  generalsettings:
    label: Seite & Footer Einstellungen
    icon: globe
    columns:
      - width: 3/4
        sections:
          content:
            type: fields
            fields:
              pageSettings:
                label: Header Einstellungen
                type: headline             

              headerScripts:
                type: textarea
                label: Header-Scripts

              customerSettings:
                label: FAQ
                type: headline
              faqHeadline:
                label: FAQ Headline
                type: text
                width: 1/2
              faqIntro:
                label: FAQ Intro
                type: textarea
                width: 1/2
              faq:
                label: FAQ
                type: structure
                style: table
                fields:
                  question: 
                    label: Question
                    type: text
                  answer:
                    label: Answer
                    type: textarea

              footerSettings:
                label: Footer Einstellungen
                type: headline
              footer_links:
                label: statische Links
                type: structure
                style: table
                fields:
                  footer_link_text:
                    label: Linktext
                    type: text
                  footer_link:
                    label: Link
                    type: text
                  footer_new_page:
                    type: toggle
                    label: auf Seite bleiben
                    default: Ja
                    text:
                       - Ja
                       - Nein

            

      - width: 1/4
        sections:
          files:
            headline: Dateien
            type: files
